acrName: acr-name
bitcoinImageTag: tag

chains:
  mainnet:
    enabled: false
    chain: main
    rpcUser: admin
    rpcPassword: null
    dbUser: mempool
    dbPassword: null
    dbRootPassword: null
    bitcoinStorage: 1Ti
    bitcoinNodeReplicas: 1
    mempoolReplicas: 3
  testnet:
    enabled: true
    chain: testnet4
    rpcUser: admin
    rpcPassword: null
    dbUser: mempool
    dbPassword: null
    dbRootPassword: null
    bitcoinStorage: 100Gi
    bitcoinNodeReplicas: 1
    mempoolReplicas: 1

ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      annotations-risk-level: Critical
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"