acrName: acr-name
bitcoinImageTag: tag

chains:
  mainnet:
    enabled: false
    chain: main
    rpcUser: admin
    rpcPassword: null
    bitcoinStorage: 1Ti
    bitcoinNodeReplicas: 1
  testnet:
    enabled: true
    chain: testnet4
    rpcUser: admin
    rpcPassword: null
    bitcoinStorage: 100Gi
    bitcoinNodeReplicas: 1