acrName: acr-name
bitcoinImageTag: tag
hostname: null

basicAuthUser: admin
basicAuthPassword: null

chains:
  mainnet:
    enabled: false
    chain: main
    rpcUser: admin
    rpcPassword: null
    dbUser: mempool
    dbPassword: null
    dbRootPassword: null
    bitcoinStorage: 1Ti
    bitcoinNodeReplicas: 1
    mempoolReplicas: 1
    spawnProcs: 3
    dbSize: 16Gi
    cacheSize: 16Gi
  testnet:
    enabled: true
    chain: testnet4
    rpcUser: admin
    rpcPassword: null
    dbUser: mempool
    dbPassword: null
    dbRootPassword: null
    bitcoinStorage: 64Gi
    bitcoinNodeReplicas: 1
    mempoolReplicas: 1
    spawnProcs: 1
    dbSize: 4Gi
    cacheSize: 4Gi

ingress-nginx:
  controller:
    allowSnippetAnnotations: true
    config:
      annotations-risk-level: Critical
    service:
      annotations:
        service.beta.kubernetes.io/azure-load-balancer-health-probe-request-path: "/healthz"
