apiVersion: v1
kind: Service
metadata:
  name: mempool-testnet-service
spec:
  type: LoadBalancer
  ports:
  - port: 8999
    protocol: TCP
    targetPort: 8999
  selector:
    app: mempool
    network: testnet
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  MARIADB_DATABASE: mempool
  MARIADB_USER: mempool
  MARIADB_PASSWORD: mempool
  MARIADB_ROOT_PASSWORD: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mempool-config
data:
  MEMPOOL_BACKEND: none
  CORE_RPC_HOST: bitcoin-testnet-service
  CORE_RPC_PORT: "48332"
  DATABASE_ENABLED: "true"
  DATABASE_HOST: localhost
  MEMPOOL_NETWORK: testnet4
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mempool-testnet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mempool
      network: testnet
  serviceName: mempool-testnet-service
  template:
    metadata:
      labels:
        app: mempool
        network: testnet
    spec:
      restartPolicy: Always
      containers:
      - name: mariadb
        image: mariadb:10.5.21
        envFrom:
        - configMapRef:
            name: db-config
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db
      - name: mempool
        image: mempool/backend:v3.0.1
        command: ["./wait-for-it.sh", "localhost:3306", "--timeout=720", "--strict", "--", "./start.sh"]
        envFrom:
        - secretRef:
            name: bitcoin-rpc-password
        - configMapRef:
            name: db-config
        - configMapRef:
            name: mempool-config
        env:
        - name: CORE_RPC_USERNAME
          value: $(BITCOIN_RPC_USERNAME)
        - name: CORE_RPC_PASSWORD
          value: $(BITCOIN_RPC_PASSWORD)
        - name: DATABASE_DATABASE
          value: $(MARIADB_DATABASE)
        - name: DATABASE_USERNAME
          value: $(MARIADB_USER)
        - name: DATABASE_PASSWORD
          value: $(MARIADB_PASSWORD)
        volumeMounts:
        - mountPath: /backend/cache
          name: cache
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: managed
  - metadata:
      name: cache
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: managed
