apiVersion: v1
kind: ConfigMap
metadata:
  name: bitcoin-conf
data:
  bitcoin.conf: |
    prune=0
    txindex=1
    server=1
    rpcallowip=0.0.0.0/0

    [main]
    rpcbind=0.0.0.0

    [testnet4]
    rpcbind=0.0.0.0