apiVersion: v1
kind: Service
metadata:
  name: bitcoin
spec:
  ports:
  - nodePort: 30002
    port: 8332
    protocol: TCP
    targetPort: 8332
  selector:
    app: bitcoin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin
  serviceName: bitcoin
  template:
    metadata:
      labels:
        app: bitcoin
    spec:
      containers:
      - image: lqoscregistry.azurecr.io/bitcoin:2961e4a2f4f3ccfa36e3288029c92e31d2c4a5b3
        name: bitcoin
        volumeMounts:
        - mountPath: /root/.bitcoin
          name: bitcoin
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: bitcoin
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Ti
      storageClassName: managed
