# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: azure-managed-disk
# spec:
#   accessModes:
#   - ReadWriteMany
#   storageClassName: managed
#   resources:
#     requests:
#       storage: 1Ti
# ---
apiVersion: v1
kind: Service
metadata:
  name: bitcoin-testnet
spec:
  selector:
    app: bitcoin-testnet
  ports:
    - protocol: TCP
      name: rpc
      port: 8332
      targetPort: 8332
    - protocol: TCP
      name: p2p
      port: 8333
      targetPort: 8333
    - protocol: TCP
      name: rpc-testnet
      port: 18332
      targetPort: 18332
    - protocol: TCP
      name: p2p-testnet
      port: 18333
      targetPort: 18333
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-testnet
spec:
  serviceName: bitcoin-testnet
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-testnet
  template:
    metadata:
      labels:
        app: bitcoin-testnet
    spec:
      restartPolicy: Always
      containers:
        - name: bitcoin-testnet
          image: viaafregistry.azurecr.io/bitcoin:67996df3aab0d82759bb56f0cdb7cac853f78fa7
          args: ["-testnet4"]
          volumeMounts:
            - name: bitcoin-testnet
              mountPath: /root/.bitcoin
  volumeClaimTemplates:
    - metadata:
        name: bitcoin-testnet
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: managed
        resources:
          requests:
            storage: 100Gi