apiVersion: v1
kind: Service
metadata:
  name: bitcoin-testnet
spec:
  ports:
  - nodePort: 30001
    port: 18332
    protocol: TCP
    targetPort: 18332
  selector:
    app: bitcoin-testnet
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-testnet
  serviceName: bitcoin-testnet
  template:
    metadata:
      labels:
        app: bitcoin-testnet
    spec:
      containers:
      - args:
        - -testnet4
        image: vxeumregistry.azurecr.io/bitcoin:a2ce3d761c79c4cef15815794e90100a77f42166
        name: bitcoin-testnet
        volumeMounts:
        - mountPath: ~/.bitcoin
          name: bitcoin-testnet
        - mountPath: '~'
          name: bitcoin-conf
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: bitcoin-conf
        name: bitcoin-conf
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-testnet
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: managed
