apiVersion: v1
kind: Service
metadata:
  name: bitcoin-testnet-service
spec:
  ports:
  - nodePort: 30001
    port: 48332
    protocol: TCP
    targetPort: 48332
  selector:
    app: bitcoin
    network: testnet
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-testnet-set
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin
      network: testnet
  serviceName: bitcoin-testnet-service
  template:
    metadata:
      labels:
        app: bitcoin
        network: testnet
    spec:
      containers:
      - args:
        - -testnet4
        - -rpcuser=$(BITCOIN_RPC_USERNAME)
        - -rpcpassword=$(BITCOIN_RPC_PASSWORD)
        envFrom:
        - secretRef:
            name: bitcoin-rpc-password
        image: lqoscregistry.azurecr.io/bitcoin:a79a002029f749475b16b54c27225b6159736698
        name: bitcoin-testnet
        volumeMounts:
        - mountPath: /root/.bitcoin
          name: datadir
        - mountPath: /root
          name: bitcoin-conf
          readOnly: true
      restartPolicy: Always
      volumes:
      - configMap:
          name: bitcoin-conf
        name: bitcoin-conf
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: managed
