apiVersion: v1
kind: Service
metadata:
  name: bitcoin-testnet
spec:
  type: LoadBalancer
  ports:
  - port: 18332
    protocol: TCP
    targetPort: 18332
    nodePort: 30001
  selector:
    app: bitcoin-testnet
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-testnet
  serviceName: bitcoin-testnet
  template:
    metadata:
      labels:
        app: bitcoin-testnet
    spec:
      containers:
      - args:
        - -testnet4
        image: viaafregistry.azurecr.io/bitcoin:bf76bc56faa0ed0cd43d1072fe9e923687082a3b
        name: bitcoin-testnet
        volumeMounts:
        - mountPath: /root/.bitcoin
          name: bitcoin-testnet
      restartPolicy: Always
  volumeClaimTemplates:
  - metadata:
      name: bitcoin-testnet
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 100Gi
      storageClassName: managed
      