{{- range $name, $config := .Values.chains -}}
{{- if $config.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoin-{{ $name }}
spec:
  replicas: {{ $config.bitcoinNodeReplicas }}
  selector:
    matchLabels:
      app: bitcoin
      chain: {{ $config.chain }}
  serviceName: bitcoin-{{ $name }}-service
  template:
    metadata:
      labels:
        app: bitcoin
        chain: {{ $config.chain }}
    spec:
      containers:
      - name: bitcoin-node
        image: {{ $.Values.acrName }}.azurecr.io/bitcoin:{{ $.Values.bitcoinImageTag }}
        args:
        - -chain={{ $config.chain }}
        - -rpcuser={{ $config.rpcUser }}
        - "-rpcpassword={{ $config.rpcPassword }}"
        volumeMounts:
        - name: datadir
          mountPath: /root/.bitcoin
        - name: files
          mountPath: /root
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - /root/readiness-probe.sh {{ $config.rpcUser }} {{ $config.rpcPassword }} {{ $config.chain }}
      restartPolicy: Always
      volumes:
        - name: files
          projected:
            defaultMode: 0555
            sources:
            - configMap:
                name: bitcoin-conf
            - configMap:
                name: bitcoin-readiness-probe
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: {{ $config.bitcoinStorage }}
      storageClassName: managed
---
{{- end -}}
{{- end -}}
