apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@generatord.io
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx
