{{- range $name, $config := .Values.chains -}}
{{- if $config.enabled -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bitcoin.mempoolStatefulsetName" $config }}
spec:
  replicas: {{ $config.mempoolReplicas }}
  selector:
    matchLabels:
      app: mempool
      chain: {{ $config.chain }}
  serviceName: {{ include "bitcoin.mempoolServiceName" $config }}
  template:
    metadata:
      labels:
        app: mempool
        chain: {{ $config.chain }}
    spec:
      restartPolicy: Always
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: mariadb
        image: mariadb:10.5.21
        envFrom:
        - configMapRef:
            name: {{ include "bitcoin.dbConfigName" $config }}
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db
      - name: mempool
        image: mempool/backend:v3.0.1
        command: ["./wait-for-it.sh", "localhost:3306", "--timeout=720", "--strict", "--", "./start.sh"]
        envFrom:
        - configMapRef:
            name: {{ include "bitcoin.mempoolConfigName" $config }}
        volumeMounts:
        - mountPath: /backend/cache
          name: cache
        readinessProbe:
          httpGet:
            path: {{ include "bitcoin.mempoolPath" $config }}/blocks/tip/height
            port: 8999
  volumeClaimTemplates:
  - metadata:
      name: db
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: managed
  - metadata:
      name: cache
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: managed
---
{{- end -}}
{{- end -}}
