{{- range $name, $config := .Values.chains -}}
{{- if $config.enabled -}}
{{- $dbName := "mempool" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoin.dbConfigName" $config }}
data:
  MARIADB_DATABASE: {{ $dbName }}
  MARIADB_USER: {{ $config.dbUser }}
  MARIADB_PASSWORD: {{ $config.dbPassword }}
  MARIADB_ROOT_PASSWORD: {{ $config.dbRootPassword }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bitcoin.mempoolConfigName" $config }}
data:
  MEMPOOL_BACKEND: none
  CORE_RPC_HOST: {{ include "bitcoin.bitcoinServiceName" $config }}
  CORE_RPC_PORT: "{{ include "bitcoin.rpcPort" $config }}"
  DATABASE_ENABLED: "true"
  DATABASE_HOST: localhost
  MEMPOOL_NETWORK: {{ include "bitcoin.mempoolNetwork" $config }}
  CORE_RPC_USERNAME: {{ $config.rpcUser }}
  CORE_RPC_PASSWORD: {{ $config.rpcPassword }}
  DATABASE_DATABASE: {{ $dbName }}
  DATABASE_USERNAME: {{ $config.dbUser }}
  DATABASE_PASSWORD: {{ $config.dbPassword }}
  MEMPOOL_API_URL_PREFIX: {{ include "bitcoin.mempoolPath" $config }}/
---
{{- end -}}
{{- end -}}
