{{- range $name, $config := .Values.chains -}}
{{- if $config.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bitcoin.mempoolServiceName" $config }}
spec:
  ports:
  - port: 8999
    protocol: TCP
    targetPort: 8999
  selector:
    app: mempool
    chain: {{ $config.chain }}
{{- end -}}
{{- end -}}
