name: Deploy Bitcoin
on:
  push:
    branches:
      - main
    paths:
      - 'k8s/bitcoin/*.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        default: 'prod'
        type: choice
        options:
          - prod
          - nonprod

permissions:
  id-token: write # Required for OIDC authentication with Azure
  contents: read
  issues: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ENVIRONMENT: ${{ inputs.environment || 'prod' }}

jobs:
  deploy-application:
    name: 'Deploy Bitcoin'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="key=terraform-$ENVIRONMENT.tfstate"
        working-directory: terraform

      - name: Get Terrform Outputs
        id: tf-outputs
        run: |
          echo "rg_name=$(terraform output -raw rg_name)" >> $GITHUB_OUTPUT
          echo "k8s_cluster_name=$(terraform output -raw k8s_cluster_name)" >> $GITHUB_OUTPUT

          btc_rpc_password=$(terraform output -raw btc_rpc_password)
          echo "::add-mask::$btc_rpc_password"
          echo "btc_rpc_password=$btc_rpc_password" >> "$GITHUB_OUTPUT"
        working-directory: terraform

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
          
      - name: Get K8s context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ steps.tf-outputs.outputs.rg_name }}
          cluster-name: ${{ steps.tf-outputs.outputs.k8s_cluster_name }}
          admin: 'false'
          use-kubelogin: 'true'
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create Secret Manifest
        run: |
          pip install -r scripts/requirements.txt
          python scripts/create-kube-rpc-password.py
        env:
          NAME: bitcoin-rpc-password
          USERNAME: admin
          SECRET: ${{ steps.tf-outputs.outputs.btc_rpc_password }}
          FILE_PATH: k8s/bitcoin/secret.yaml

      - name: Deploy Setup Manifests
        run: |
          kubectl apply -f k8s/bitcoin/secret.yaml
          kubectl apply -f k8s/bitcoin/bitcoin-conf.yaml

      - name: Deploy Testnet
        run: kubectl apply -f k8s/bitcoin/testnet.yaml

      - name: Await Approval
        if: ${{ env.ENVIRONMENT == 'prod' }}
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: Vanniix
          issue-title: "Approval of Mainnet Deployment"
          issue-body: "Do you want to deploy mainnet?"
      
      - name: Deploy Mainnet
        run: kubectl apply -f k8s/bitcoin/mainnet.yaml