name: Deploy Application
on:
  push:
    branches:
      - main
    paths:
      - 'k8s/**/*.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        default: 'prod'
        type: choice
        options:
          - prod
          - nonprod

permissions:
  id-token: write # Required for OIDC authentication with Azure
  contents: read
  issues: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ENVIRONMENT: ${{ inputs.environment || 'prod' }}

jobs:
  deploy-application:
    name: 'Deploy Bitcoin'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Get Terrform Outputs
        id: tf-outputs
        run: |
          terraform init -backend-config="key=terraform-$ENVIRONMENT.tfstate"
          echo "rg_name=$(terraform output -raw rg_name)" >> $GITHUB_OUTPUT
          echo "kube_cluster_name=$(terraform output -raw kube_cluster_name)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
          
      - name: Get Kube Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ steps.tf-outputs.outputs.rg_name }}
          cluster-name: ${{ steps.tf-outputs.outputs.kube_cluster_name }}
          admin: 'false'
          use-kubelogin: 'true'
      
      - name: Deploy Mainnet
        run: |
          acr_name=$(terraform output -raw acr_name)
          image_tag=$(az acr repository show-tags --n $acr_name --repository bitcoin \
            --orderby time_desc --top 1 --output tsv)
          passwords=$(terraform output -json passwords)
          helm upgrade --install bitcoin ../helm/bitcoin \
            --set acrName=$acr_name \
            --set bitcoinImageTag=$image_tag \
            --set chains.mainnet.enabled=${{ env.ENVIRONMENT == 'prod' }} \
            --set chains.testnet.rpcPassword="$($passwords | jq -r '."testnet-rpc"')" \
            --set chains.mainnet.rpcPassword="$($passwords | jq -r '."mainnet-rpc"')" \
            --set chains.testnet.dbPassword="$($passwords | jq -r '."testnet-db"')" \
            --set chains.mainnet.dbPassword="$($passwords | jq -r '."testnet-db"')" \
            --set chains.testnet.dbRootPassword="$($passwords | jq -r '."testnet-db-root"')" \
            --set chains.mainnet.dbRootPassword="$($passwords | jq -r '."testnet-db-root"')"
        working-directory: terraform