name: Deploy Application
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        default: 'prod'
        type: choice
        options:
          - prod
          - nonprod

permissions:
  id-token: write # Required for OIDC authentication with Azure
  contents: read
  issues: write

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  ENVIRONMENT: ${{ inputs.environment || 'prod' }}

jobs:
  deploy-application:
    name: 'Deploy Application'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      - name: Get Terrform Outputs
        id: tf-outputs
        run: |
          terraform init -backend-config="key=terraform-$ENVIRONMENT.tfstate"
          echo "rg_name=$(terraform output -raw rg_name)" >> $GITHUB_OUTPUT
          echo "kube_cluster_name=$(terraform output -raw kube_cluster_name)" >> $GITHUB_OUTPUT
        working-directory: terraform

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
          
      - name: Get Kube Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ steps.tf-outputs.outputs.rg_name }}
          cluster-name: ${{ steps.tf-outputs.outputs.kube_cluster_name }}
          admin: 'false'
          use-kubelogin: 'true'
      
      - name: Deploy
        run: |
          acr_name=$(terraform output -raw acr_name)
          image_tag=$(az acr repository show-tags --n $acr_name --repository bitcoin \
            --orderby time_desc --top 1 --output tsv)
          passwords=$(terraform output -json passwords)

          helm repo add kubernetes https://kubernetes.github.io/ingress-nginx
          helm repo add jetstack https://charts.jetstack.io

          helm upgrade --install cert-manager jetstack/cert-manager \
            --version v1.16.2 \
            --set crds.enabled=true

          helm dependency build ../helm/bitcoin
          helm upgrade --install bitcoin ../helm/bitcoin \
            --set acrName=$acr_name \
            --set bitcoinImageTag=$image_tag \
            --set chains.mainnet.enabled=${{ env.ENVIRONMENT == 'prod' }} \
            --set chains.testnet.rpcPassword="$(echo $passwords | jq -r '."testnet-rpc"')" \
            --set chains.mainnet.rpcPassword="$(echo $passwords | jq -r '."mainnet-rpc"')" \
            --set chains.testnet.dbPassword="$(echo $passwords | jq -r '."testnet-db"')" \
            --set chains.mainnet.dbPassword="$(echo $passwords | jq -r '."mainnet-db"')" \
            --set chains.testnet.dbRootPassword="$(echo $passwords | jq -r '."testnet-db-root"')" \
            --set chains.mainnet.dbRootPassword="$(echo $passwords | jq -r '."mainnet-db-root"')"
        working-directory: terraform
    
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm ci
          npm run start
        working-directory: dns
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          DOMAIN: 'generatord.io'
          SUB_DOMAIN: bitcoin
          TEAM_SLUG: fomojis
